version: '2.4'
services:
    api-manager:
      image: wso2am:4.0.0
      healthcheck:
        test: ["CMD", "nc", "-z","localhost", "9443"]
        interval: 10s
        start_period: 180s
        retries: 20
      ports:
      - "9443:9443"
      - "8280:8280"
      - "8243:8243"
      - "9099:9099"
      - "9021:9021"
      depends_on:
        mi-runtime:
          condition: service_healthy 
        si-runtime:
          condition: service_healthy
      volumes:
      - ./dockerfiles/conf/apim:/home/wso2carbon/wso2-config-volume
    mi-runtime:
      build: 
        context: ./dockerfiles/micro-integrator/
        args:
          - BASE_IMAGE=wso2/wso2mi:4.0.0-alpha
      healthcheck:
        test: ["CMD", "nc", "-z","localhost", "8290"]
        interval: 10s
        start_period: 30s
        retries: 20
      ports:
      - "8253:8253"
      - "8290:8290"
      - "9201:9201"
      mem_limit: 512m
      mem_reservation: 128M
      cpus: 1
      depends_on:
        db:
          condition: service_healthy
    si-runtime:
      build: 
        context: ./dockerfiles/streaming-integrator/
        args:
          - BASE_IMAGE=wso2/wso2si:4.0.0
      healthcheck:
        test: ["CMD", "nc", "-z","localhost", "9090"]
        interval: 10s
        start_period: 30s
        retries: 20
      ports:
      - "8025:8025"
      - "9090:9090"
      mem_limit: 512m
      mem_reservation: 128M
      cpus: 0.5
    backend-service:
      build: ./dockerfiles/backends/
      healthcheck:
        test: ["CMD", "nc", "-z","localhost", "8080"]
        interval: 10s
        start_period: 30s
        retries: 20
      ports:
      - "8082:8080"
      mem_limit: 512m
      mem_reservation: 128M
      cpus: 0.5
    db:
      image: mysql:8.0.23
      ports:
        - 8083:3306
      command: --init-file /data/application/init.sql
      volumes:
        - ./dockerfiles/database/init.sql:/data/application/init.sql
      environment:
        MYSQL_ROOT_PASSWORD: pwd
        MYSQL_DATABASE: mysql
      healthcheck:
        test: ["CMD", "mysqladmin" ,"ping", "-uroot", "-proot"]
        interval: 30s
        timeout: 60s
        retries: 5
        start_period: 80s
      mem_limit: 512m
      mem_reservation: 128M
      cpus: 0.5
    scripts:
      build: ./dockerfiles/scripts
      mem_limit: 256m
      mem_reservation: 128M
      cpus: 0.25
      environment:
        APIM_HOST : api-manager
        RETRY_SEC : 5
        RE_RUN: 'false'