version: '2.4'
services:
    api-manager:
      image: chamilaadhi/wso2am:4.0.0_20210317
      healthcheck:
        test: ["CMD", "nc", "-z","localhost", "9443"]
        interval: 10s
        start_period: 150s
        retries: 25
      ports:
      - "9443:9443"
      - "8280:8280"
      - "8243:8243"
      - "9099:9099"
      - "9021:9021"
      volumes:
      - ./dockerfiles/conf/apim:/home/wso2carbon/wso2-config-volume
    mi-runtime:
      build: 
        context: ./dockerfiles/micro-integrator/
        args:
          - BASE_IMAGE=wso2/wso2mi:4.0.0-alpha
      healthcheck:
        test: ["CMD", "nc", "-z","localhost", "8290"]
        interval: 10s
        start_period: 30s
        retries: 20
      ports:
      - "8253:8253"
      - "8290:8290"
      - "9201:9201"
      mem_limit: 1G
      mem_reservation: 128M
      cpus: 1
      depends_on:
        db:
          condition: service_healthy
        # for service-catalog  
        api-manager:
          condition: service_healthy
      volumes:
        - ~/mytmp/csvin:/home/wso2carbon/sample/in
        - ~/mytmp/csvout:/home/wso2carbon/sample/out
        - ~/mytmp/csverror:/home/wso2carbon/sample/error
      environment:
        # CATERING_BE : test
        SMTP_HOST: <smtp_server_host>
        SMTP_PORT: <smtp_server_port>
        SMTP_USERNAME: <smtp_server_username>
        SMTP_PASSWORD: <smtp_server_password>
    si-runtime:
      build: 
        context: ./dockerfiles/streaming-integrator/
        args:
          - BASE_IMAGE=chamilaadhi/wso2si:4.0.0_alpha
      healthcheck:
        test: ["CMD", "nc", "-z","localhost", "9090"]
        interval: 10s
        start_period: 30s
        retries: 20
      ports:
      - "8025:8025"
      - "9090:9090"
      mem_limit: 512m
      mem_reservation: 128M
      cpus: 0.5
      depends_on: 
        # for service-catalog  
        api-manager:
          condition: service_healthy
    backend-service:
      build: ./dockerfiles/backends/
      healthcheck:
        test: ["CMD", "nc", "-z","localhost", "8080"]
        interval: 10s
        start_period: 30s
        retries: 20
      ports:
      - "8082:8080"
      mem_limit: 512m
      mem_reservation: 128M
      cpus: 1
    db:
      image: mysql:8.0.23
      ports:
        - 8083:3306
      command: --init-file /data/application/init.sql
      volumes:
        - ./dockerfiles/database/init.sql:/data/application/init.sql
      environment:
        MYSQL_ROOT_PASSWORD: pwd
        MYSQL_DATABASE: mysql
      healthcheck:
        test: ["CMD", "mysqladmin" ,"ping", "-uroot", "-proot"]
        interval: 10s
        retries: 20
        start_period: 10s
      mem_limit: 512m
      mem_reservation: 128M
      cpus: 0.5
    scripts:
      build: ./dockerfiles/scripts
      mem_limit: 256m
      mem_reservation: 128M
      cpus: 1
      environment:
        APIM_HOST : api-manager
        RETRY_SEC : 5
        RE_RUN: 'false'
      depends_on:
        api-manager:
          condition: service_healthy