version: '2.4'
services:
    api-manager:
      image: wso2am:4.0.0
      healthcheck:
        test: ["CMD", "nc", "-z","localhost", "9443"]
        interval: 10s
        start_period: 180s
        retries: 20
      ports:
      - "9443:9443"
      - "8280:8280"
      - "8243:8243"
    mi:
      image: wso2mi:4.0.0
      healthcheck:
        test: ["CMD", "nc", "-z","localhost", "8290"]
        interval: 10s
        start_period: 60s
        retries: 20
      ports:
      - "8253:8253"
      - "8290:8290"
      mem_limit: 512m
      mem_reservation: 128M
      cpus: 0.5
    backend-service:
      build: ./dockerfiles/backends/
      healthcheck:
        test: ["CMD", "nc", "-z","localhost", "8080"]
        interval: 10s
        start_period: 30s
        retries: 20
      ports:
      - "8082:8080"
      mem_limit: 512m
      mem_reservation: 128M
      cpus: 0.5
    scripts:
      build: ./dockerfiles/scripts
      mem_limit: 512m
      mem_reservation: 128M
      cpus: 0.5